# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib rdz, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_rdz__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_rdz__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`rdz_file_info` <- function(`path`) {
  .Call(savvy_rdz_file_info__impl, `path`)
}


`rdz_read` <- function(`path`) {
  .Call(savvy_rdz_read__impl, `path`)
}


`rdz_read_native_names` <- function(`path`) {
  .Call(savvy_rdz_read_native_names__impl, `path`)
}


`rdz_root_length` <- function(`x`) {
  .Call(savvy_rdz_root_length__impl, `x`)
}


`rdz_try_write_native` <- function(`x`, `path`, `strict`) {
  .Call(savvy_rdz_try_write_native__impl, `x`, `path`, `strict`)
}


`rdz_write_generic` <- function(`payload`, `synopsis`, `path`) {
  invisible(.Call(savvy_rdz_write_generic__impl, `payload`, `synopsis`, `path`))
}


